name: Check Links In Pull Requests
permissions: {}

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Checkout base branch
        run: git checkout ${{ github.event.pull_request.base.ref }}

      - name: Get list of changed Markdown files
        id: changed-files
        run: |
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}...${{ github.head_ref }} -- '*.md' > changed-files.txt
          cat changed-files.txt
          
      - name: Exit early if no Markdown files changed
        run: |
          if [ ! -s changed-files.txt ]; then
            echo "No Markdown files changed. Skipping link check."
            exit 0
          fi

      - name: Switch to PR branch
        run: git checkout ${{ github.head_ref }}

      - name: Check links in changed files
        uses: lycheeverse/lychee-action@v2
        with:
          failIfEmpty: false
          args: |
            --no-progress
            $(cat changed-files.txt | tr '\n' ' ')

      - name: Provide helpful failure message
        if: failure()
        run: |
          echo "::error::Link check failed! Please review the broken links reported above."
          echo ""
          echo "If certain links are valid but fail due to:"
          echo "- CAPTCHA challenges"
          echo "- IP blocking"
          echo "- Authentication requirements"
          echo "- Rate limiting"
          echo ""
          echo "Consider adding them to .lycheeignore to bypass future checks."
          echo "Format: Add one URL pattern per line"
          exit 1
